### ISSUE TITLE
Add TypeScript build step before publish?

### ISSUE THREAD

**Issue by eliot-akira** [josephg/node-fdb#1]
If a project that imports this module doesn't use TypeScript, it results in an error: `Cannot find module 'foundationdb'`. I believe this is due to the following line in `package.json`:

```json
  "main": "dist/index.js"
```

The module `foundationdb` published on npm doesn't have a `dist` folder.

Perhaps TypeScript should be compiled in a `prepublish` script?

```json
  "scripts": {
    "install": "node-gyp rebuild",
    "prepublish": "tsc -p ."
  }
```

..and add `!dist` in a new `.npmignore` (to exclude from repo but include in published module)?

**Comment by josephg** [comment]
Oh oops, yeah. I had that working in an earlier published version. That’s what I intended I just forgot. I’ll republish in a bit.

**Comment by josephg** [comment]
You're welcome to make PRs for this sort of stuff. Anyway, fixed and republished.
