### ISSUE TITLE
Add link to repo in package.json?

### ISSUE THREAD

**Issue by eliot-akira** [josephg/node-fdb#2]
Would be nice to provide a link to the source repo, to be displayed on [this module's npm page](https://www.npmjs.com/package/foundationdb).

Something like:

```json
  "repository": {
    "type": "git",
    "url": "git+https://github.com/josephg/node-fdb.git"
  }
```

Since this module is so freshly published, maybe you're waiting until it gets more mature to move to an official repo?

**Comment by josephg** [comment]
Good catch. Fixed
