### ISSUE TITLE
Error when using `require` instead of `import`

### ISSUE THREAD

**Issue by eliot-akira** [josephg/node-fdb#3]
The example code in `README.md` results in an error: `fdb.openSync is not a function`. This is because the following line:

```js
const fdb = require('foundationdb')
```

..results in importing an object of the shape:

```js
{
  default: {
    FDBError: [Function: FDBError],
    configNetwork: [Function: configNetwork],
    ...
  }
}
```

So I had to require the module like this:

```js
const fdb = require('foundationdb').default
```

Related to: [Microsoft/TypeScript#2719 - ES6 Modules default exports interop with CommonJS](Microsoft/TypeScript#2719)

**Comment by josephg** [comment]
Thanks for catching that. Fixed & republished.
